name: VariantCalling

on:
  push:
    branches: ["main", "dev", "ci"]
  pull_request:
    branches: ["main"]

jobs:
  VariantCalling:
    name: VariantCalling CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: defaults,bioconda,conda-forge
          channel-priority: true
          auto-activate-base: true

      - name: Check conda installation
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Install nextflow
        run: |
          conda install -c bioconda nextflow
          nextflow -version

      - name: Check CovPipe2 presence
        run: nextflow run CoVpipe2.nf --help
        
      - name: Git checkout CIEVaD + REF
        run: |
            eval `ssh-agent -s`
            ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
            git clone git@github.com:rki-mf1/cievad.git
            pushd cievad
            wget https://www.ebi.ac.uk/ena/browser/api/fasta/MN908947.3
            sed 's/>ENA|MN908947|MN908947.3 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome./>MN908947.3/g' MN908947.3 > MN908947.3.fasta
            popd

      - name: Run CIEVaD hap
        run: |
            pushd cievad
            nextflow run hap.nf -profile local,conda --reference MN908947.3.fasta
            ls -la results/simulated_hap*NGSWGS*.fastq
            popd

      - name: Run CovPipe2
        run: |
            # BECAUSE CIEVAD'S DEFAULT IS N=3 SAMPLES
            NB_SAMPLES=3
            echo "sample,fastq_1,fastq_2" > samplesheet.csv
            for s in $(seq 1 $NB_SAMPLES); do echo "hap${s},cievad/results/simulated_hap${s}.NGSWGS.R1.fastq,cievad/results/simulated_hap${s}.NGSWGS.R2.fastq" >> samplesheet.csv; done
            cat samplesheet.csv
            nextflow run rki-mf1/CoVpipe2 \
              -r v0.4.2 \
              -profile local,conda \
              -w work \
              --output results \
              --reference 'sars-cov-2' \
              --fastq samplesheet.csv --list \
              --primer_version V3
            ls -la results/03-Variant-Calling/simulated_hap*/simulated_hap*.filtered.gt_adjust.filtered_indels.vcf.gz



  #    - name: dry run
  #     run: |
  #         touch reads_1.fastq reads_2.fastq
  #         nextflow run CoVpipe2.nf --fastq reads_{1,2}.fastq --reference sars-cov-2 --cores 2 --max_cores 2 -stub -profile stub
