name: VariantCalling

on:
  push:
    branches: [main, dev, ci]
  pull_request:
    branches: [main]

jobs:
  VariantCalling:
    name: VariantCalling CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: defaults,bioconda,conda-forge
          channel-priority: true
          auto-activate-base: true

    - name: Check conda installation
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show

    - name: Install nextflow
      run: |
        conda install -c bioconda nextflow
        nextflow -version

    - name: Check CovPipe2 presence
      run: nextflow run CoVpipe2.nf --help
      
#    - name: dry run
#     run: |
#         touch reads_1.fastq reads_2.fastq
#         nextflow run CoVpipe2.nf --fastq reads_{1,2}.fastq --reference sars-cov-2 --cores 2 --max_cores 2 -stub -profile stub
